### PR TITLE
Problem: we need that tntnet was able to read shadow file

### PR DESCRIPTION
**Pull request by barraudl**
Signed-off-by: barraudl <lilianbarraud@eaton.com>

### CODE REVIEW

**Comment by jimklimov** [comment]
Do you have any solution that does not require the webserver (running arbitrary code of our and potentially third-party servlets in a complicated and barely auditable state machine) to have too many privileges? Abusing some leak over HTTP to snatch password ciphers is a neat first step to cracking them "offline" and then using the result to get into the system.

**Comment by EldoreiJK** [comment]
Seconded, please check for other solution that won't introduce such a big cyber security issue - since there is a cyber security focus coming soon, this would need to be addressed either way, so I'd prefer to have it addressed now. Thank you.

**Comment by jana-rapava** [comment]
I agree with Jiri - I am afraid this won't pass cyber security audit and we need to come up with other solution. What problem are you trying to solve?

**Comment by EldoreiJK** [comment]
I suggest to create a separate daemon that will act as a proxy (or implement actions) for password management (or better - whole user management) and will run with sufficient privileges.

**Comment by geraldguillaume** [comment]
Consider this as temporary solution, we are working a better approach to avoid this annoying security issue.

**Comment by geraldguillaume** [comment]
Hopefully we decided to go with a different approach, so abandon it

**Pull request closed without merging**
