### PR TITLE
Add file for 2.1.0 update with increase of extattribut key size

### PR DESCRIPTION
**Pull request by perrettecl**

### CODE REVIEW

**Comment by boricj** [comment]
This file does not follow the normal naming convention for DB update scripts. Will it work fine both on upgrade and on initial deployment?

**Comment by jimklimov** [comment]
Seconding JB's comment - not-yet-seen sql snippet files are applied by fty-db-init in alphanumeric order. This file name might work in upgrades where older files were applied earlier, but on a fresh install it would likely try to change the schema which is not defined yet.

Just add it in alphabetic-prefix order after existing files.

**Comment by jimklimov** [comment]
Also attributE is spelled with E in the end ;)

**Review by jimklimov — CHANGES_REQUESTED** [review]
SQL file must be renamed (in Makefile and its own metadata entries too), typos optionally fixed.

**Comment by perrettecl** [comment]
I did differently. We should stop to use this numbered file and have only 1 file for each release.

**Pull request closed without merging**
