### PR TITLE
[DNMY] Fix jessie 1.5.0

### PR DESCRIPTION
**Pull request by jimklimov**

### CODE REVIEW

**Comment by jana-rapava** [comment]
This PR is made in preparation for moving jessie-backports to archive. It should be merged after this move happens.

**Comment by aquette** [comment]
@jimklimov should be good to merge now, no?

**Comment by jimklimov** [comment]
I think it should be ok to merge. I am not sure what the situation is with `jessie-updates` vs.  `jessie/updates` - I haven't found the former (with dash) "pseudo-distro" in any of the sources last I looked. Maybe it is a legacy artifact (seems a few older releases had such repo naming pattern) or just a typo? Does not seem to impact anything in practice either, though may be responsible for a few warning/error messages here and there in `apt-get update` runs.

**Comment by aquette** [comment]
jessie-update is pre-release of what then ends up in point release. Get reset (emptied) every new point release. I've not checked further, but the last one (8.11) was around mid 2018. 

jessie/updates is the security channel, tied to security.d.o

**Pull request merged**
