### PR TITLE
run-ssh-action script cleanup

### PR DESCRIPTION
**Pull request by jimklimov**
Follows up from #454 comments that were ignored.

### CODE REVIEW

**Review by perrettecl — CHANGES_REQUESTED** [review]
Please run shellcheck to fix all the issues (On your free time as it's FOSS contribution)

**Comment by jimklimov** [comment]
> Please run shellcheck to fix all the issues (On your free time as it's FOSS contribution and not on your backlog)

This was checked before contribution, neither `bash -n`, `dash -n` nor `busybox sh -n` complained.

**Review by boricj — APPROVED** [review]

**Comment by jimklimov** [comment]
I assume you mean the shellcheck project that's half a year old, did not reach a 1.x version yet and has about as many open issues as commits?

Sarcasm aside, seems reasonable but alas is not in our quality gates, automated tests nor build environment, so the immediate suggestion is bogus (not to mention that your original script obviously did not pass and the remaining few errors are from it), but long-term idea is commendable, especially when shellcheck matures and its diagnoses and suggestions are reliable and dependable. I'll be happy to review your integration of it into the auto-testing stack. For now we stick to syntax checks by shell(s) invovled and common scripting know-how which is not as easy to automate, true.

**Comment by jimklimov** [comment]
Now also shellcheck-clean, and got a slight security issue fixed.

**Comment by jimklimov** [comment]
> Please run shellcheck to fix all the issues (On your free time as it's FOSS contribution and not on your backlog)

I believe this requested fix can be accepted

**Pull request merged**
