### PR TITLE
Problem : OVA image sometime register its hostname to default localhost to the DHCP srv

### PR DESCRIPTION
**Pull request by geraldguillaume**
My hypothesis is that sometime the "$reason" does not belong to the list bound|renew|BOUND|RENEW|REBIND|REBOOT, so we failed in the default case which return, so we lost the chance to initialize properly the hostname.
Solution, do not take in account the "$raeson" to force the hostname initialization happening in every cases.

Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>

### CODE REVIEW

**Comment by jimklimov** [comment]
We can try, though i'd prefer to investigate this by keeping the original logic and logging that we bail on unsupported reason.

Also, seems this routine uses a `$hostname` value (if any) set by DHCP client and then manipulates the saved value in /etc/hostname as well as applied to locally running kernel. It does not directly feed back to DHCP server here.

**Comment by aquette** [comment]
though I agree with you @jimklimov that it's better to understand the root cause, I don't see why the hostname setup should be bound to a limited set of $reason. All the hostname logic should be done, whatever the reason is! Or do I miss something @jimklimov?
Still, @geraldguillaume could you please restore the case block, add a trace (or a bmsg alarm) + comment the "return" in the "*)" case. That will leave a chance to understand and fix properly

**Comment by boricj** [comment]
As long as the hostname setup is idempotent and cheap, I don't see a problem with it running repeatedly (within reason). What I don't want to see is 30+ VMs on the dev network all claiming to be `localhost` and forcing everyone to use IP addresses because name resolution is broken.

**Comment by aquette** [comment]
If there are so many and not just a few, it should be easy to reproduce, log, understand and fix 😉

**Comment by jimklimov** [comment]
Claiming localhost in dns requires that a dhcp request is sent with `-o hostname` option, and dhcp server forwards the assigned name for an IP address to the dns server.

So as long as this hook script does not send the query, it is not the direct cause of such hostname. (Might be indirect, where something else registers the name, and it happens to be the localhost default coming from nonidea where). Lack of init code in OVA loader compared to IPC loader (here, to set the initial name) is the more likely cause.

Also, without reading into the dhcp protocol spec and/or client sources, I can not guarantee if there are not some $reason's where this script should really abort, or if it is ok to run in any context (as long as it avoids writing same data to flash). Can you? :)

**Comment by aquette** [comment]
@boricj @geraldguillaume any update on this issue? Were you able to make some tests?

**Pull request merged**
