### PR TITLE
[IPMPROG-440] envvars-ExecStartPre.sh: propagate OSIMAGE_VENDOR and HARDWARE_VENDOR…

### PR DESCRIPTION
**Pull request by jimklimov**
… from available system data

### CODE REVIEW

**Review by perrettecl — CHANGES_REQUESTED** [review]
Not sure we ask about having those propagated. Can you provide details why it's needed?

**Comment by jimklimov** [comment]
TBH, currently no exact known need indeed, as there are no consumers of these newly introduced envvars. But since we have generally consumers of hardware-vendor (directly from json) and of hw-model and similar data points (via envvars exported from this generated file to our services with common unit file setup), somehow it made sense to make these known.

For update-rc3 in particular, when/if it is used to pull updates from a download site modeled after our internal store (or in CI tests), the image vendor would be part of the URL path.

**Comment by jimklimov** [comment]
One more point in favor of this PR - the casing of the vendor as placed into manifest, it is lost when it goes to release-details.json (upper-cased when transplanted, to allow for UUID seeding). So if we need to emit messages etc. with original spelling of that vendor, we want a field that conveys it. And since that vendor data is dictated by the software-only OS image, well... it is not a hardware vendor for sure :)

**Comment by jimklimov** [comment]
Bumped to expose the difference of HARDWARE_VENDOR (e.g. "EATON") vs. HARDWARE_MANUFACTURER (e.g. for VMs it would be like "VMWare Inc." or "innotek Gmbh")

**Pull request merged**
