### PR TITLE
Remove unused services

### PR DESCRIPTION
**Pull request by MimiXav**
Remove only bios-agent-inventory and bios-fake-th services only

### CODE REVIEW

**Comment by jimklimov** [comment]
Looks ok for the short run (of not-having these services in newly built images), but as discussed there should also be a `setup/*.sh` scriptlet that ipc-meta-setup service would run once when some OS image that contains it boots for the first time on the deployment, to clean up references to these services set up earlier (essentially systemctl `stop||true` + `disable||true` to unregister these, if at all present) to handle upgrades cleanly.

**Comment by jimklimov** [comment]
Also, please use private developer forks for making PRs, from branches that are not intended as feature images, releases, etc. CI has a complicated time already tracking all the branches our common upstream projects have. Thanks ;)

**Comment by jimklimov** [comment]
Decided to merge a bit later, after we stabilize the image broken by unrelated changes before team NY vacations.

**Comment by stark-dev** [comment]
Hi! Just to let you know I merged another PR (my fault, I didn't see those were approved already). Btw, I touched other files, so this should be merged anyway. My apologies, have a nice weekend!

**Pull request merged**
